const users = require("../src/models/usersModel");

const seedUsers = async () => {
  const users = [
    {
      name: "John Doe",
      email: "john.doe@example.com",
      age: 30,
      role: "Admin",
      isActive: true,
      password: "John",
    },
    {
      name: "Jane Smith",
      email: "jane.smith@example.com",
      age: 28,
      role: "User",
      isActive: true,
      password: "Jane",
    },
    {
      name: "Emily Brown",
      email: "emily.brown@example.com",
      age: 35,
      role: "User",
      isActive: false,
      password: "Emily",
    },
    {
      name: "Michael Johnson",
      email: "michael.johnson@example.com",
      age: 40,
      role: "Admin",
      isActive: true,
      password: "Michael",
    },
    {
      name: "Samantha Williams",
      email: "samantha.williams@example.com",
      age: 22,
      role: "User",
      isActive: true,
      password: "Samantha",
    },
    {
      name: "David Miller",
      email: "david.miller@example.com",
      age: 45,
      role: "Admin",
      isActive: false,
      password: "David",
    },
    {
      name: "Chris Davis",
      email: "chris.davis@example.com",
      age: 32,
      role: "User",
      isActive: true,
      password: "Chris",
    },
    {
      name: "Laura Martinez",
      email: "laura.martinez@example.com",
      age: 27,
      role: "Admin",
      isActive: true,
      password: "Laura",
    },
    {
      name: "Daniel Garcia",
      email: "daniel.garcia@example.com",
      age: 38,
      role: "User",
      isActive: false,
      password: "Daniel",
    },
    {
      name: "Sophia Taylor",
      email: "sophia.taylor@example.com",
      age: 24,
      role: "Admin",
      isActive: true,
      password: "Sophia",
    },
    {
      name: "Jack Wilson",
      email: "jack.wilson@example.com",
      age: 29,
      role: "User",
      isActive: true,
      password: "Jack",
    },
    {
      name: "Olivia Moore",
      email: "olivia.moore@example.com",
      age: 34,
      role: "Admin",
      isActive: false,
      password: "Olivia",
    },
    {
      name: "Ethan White",
      email: "ethan.white@example.com",
      age: 26,
      role: "User",
      isActive: true,
      password: "Ethan",
    },
    {
      name: "Avery Harris",
      email: "avery.harris@example.com",
      age: 39,
      role: "Admin",
      isActive: true,
      password: "Avery",
    },
    {
      name: "Lucas Clark",
      email: "lucas.clark@example.com",
      age: 33,
      role: "User",
      isActive: false,
      password: "Lucas",
    },
    {
      name: "Lily Lewis",
      email: "lily.lewis@example.com",
      age: 25,
      role: "Admin",
      isActive: true,
      password: "Lily",
    },
    {
      name: "Mason Young",
      email: "mason.young@example.com",
      age: 31,
      role: "User",
      isActive: true,
      password: "Mason",
    },
    {
      name: "Charlotte King",
      email: "charlotte.king@example.com",
      age: 27,
      role: "Admin",
      isActive: false,
      password: "Charlotte",
    },
    {
      name: "James Scott",
      email: "james.scott@example.com",
      age: 40,
      role: "User",
      isActive: true,
      password: "James",
    },
    {
      name: "Benjamin Adams",
      email: "benjamin.adams@example.com",
      age: 34,
      role: "Admin",
      isActive: true,
      password: "Benjamin",
    },
    {
      name: "Zoe Baker",
      email: "zoe.baker@example.com",
      age: 29,
      role: "User",
      isActive: true,
      password: "Zoe",
    },
    {
      name: "Henry Nelson",
      email: "henry.nelson@example.com",
      age: 38,
      role: "Admin",
      isActive: false,
      password: "Henry",
    },
    {
      name: "Chloe Carter",
      email: "chloe.carter@example.com",
      age: 24,
      role: "User",
      isActive: true,
      password: "Chloe",
    },
    {
      name: "William Perez",
      email: "william.perez@example.com",
      age: 32,
      role: "Admin",
      isActive: true,
      password: "William",
    },
    {
      name: "Isabella Rodriguez",
      email: "isabella.rodriguez@example.com",
      age: 26,
      role: "User",
      isActive: false,
      password: "Isabella",
    },
    {
      name: "Alexander Murphy",
      email: "alexander.murphy@example.com",
      age: 36,
      role: "Admin",
      isActive: true,
      password: "Alexander",
    },
    {
      name: "Evelyn Gray",
      email: "evelyn.gray@example.com",
      age: 33,
      role: "User",
      isActive: true,
      password: "Evelyn",
    },
    {
      name: "Matthew Walker",
      email: "matthew.walker@example.com",
      age: 41,
      role: "Admin",
      isActive: false,
      password: "Matthew",
    },
    {
      name: "Amelia Hall",
      email: "amelia.hall@example.com",
      age: 28,
      role: "User",
      isActive: true,
      password: "Amelia",
    },
    {
      name: "Daniel Allen",
      email: "daniel.allen@example.com",
      age: 45,
      role: "Admin",
      isActive: true,
      password: "Daniel",
    },
    {
      name: "Mia King",
      email: "mia.king@example.com",
      age: 37,
      role: "User",
      isActive: true,
      password: "Mia",
    },
    {
      name: "Joshua Wright",
      email: "joshua.wright@example.com",
      age: 30,
      role: "Admin",
      isActive: false,
      password: "Joshua",
    },
    {
      name: "Abigail Green",
      email: "abigail.green@example.com",
      age: 34,
      role: "User",
      isActive: true,
      password: "Abigail",
    },
    {
      name: "Elijah Harris",
      email: "elijah.harris@example.com",
      age: 28,
      role: "Admin",
      isActive: true,
      password: "Elijah",
    },
    {
      name: "Grace Carter",
      email: "grace.carter@example.com",
      age: 22,
      role: "User",
      isActive: false,
      password: "Grace",
    },
    {
      name: "Samuel Mitchell",
      email: "samuel.mitchell@example.com",
      age: 29,
      role: "Admin",
      isActive: true,
      password: "Samuel",
    },
    {
      name: "Natalie Thomas",
      email: "natalie.thomas@example.com",
      age: 32,
      role: "User",
      isActive: true,
      password: "Natalie",
    },
    {
      name: "Jackson Rodriguez",
      email: "jackson.rodriguez@example.com",
      age: 36,
      role: "Admin",
      isActive: false,
      password: "Jackson",
    },
    {
      name: "Ariana Perez",
      email: "ariana.perez@example.com",
      age: 27,
      role: "User",
      isActive: true,
      password: "Ariana",
    },
    {
      name: "Carter Hughes",
      email: "carter.hughes@example.com",
      age: 30,
      role: "Admin",
      isActive: true,
      password: "Carter",
    },
    {
      name: "Victoria Wilson",
      email: "victoria.wilson@example.com",
      age: 33,
      role: "User",
      isActive: true,
      password: "Victoria",
    },
    {
      name: "David Moore",
      email: "david.moore@example.com",
      age: 41,
      role: "Admin",
      isActive: false,
      password: "David",
    },
    {
      name: "Zara Scott",
      email: "zara.scott@example.com",
      age: 34,
      role: "User",
      isActive: true,
      password: "Zara",
    },
  ];

  try {
    await users.bulkCreate(users);
    console.log("User seeded successfully!!!");
  } catch (error) {
    console.error(error);
  }
};

seedUsers();
